tiger.api.key=${TIGER_API_KEY:}
tiger.api.secret=${TIGER_API_SECRET:MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCAtlhYOFHZ/a3BWzaspg6iv9cVfraD69LYWqnIQ7HPq/iv+qsuuJICr2gmk1aRZR4/c+wXNtqDdrfW/Uoy8Ivw+uBzlnH0lvcaQVIv8RhiJYkf0GDH8D0EKhiOv9K2zYVv96ozGGca905AX9i/FL8mWMnyfW/M9HC0s6RhbyvFXwIDAQAB}
tiger.api.url=${TIGER_API_URL:https://openapi.itigerup.com}
